name: Deploy to Render

on:
  push:
    branches:
      - deployment

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout deployment branch
      uses: actions/checkout@v3

    - name: Checkout main branch (models)
      uses: actions/checkout@v3
      with:
        ref: main
        path: main_branch

    - name: Copy models from main â†’ deployment
      run: |
        mkdir -p ml_models/models
        cp -r main_branch/models/* ml_models/models/
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ml_models/models
        git commit -m "Synced models from main branch" || echo "No changes to commit"

    - name: Push updated model files to deployment branch
      run: |
        git push origin deployment

    - name: Trigger Render Deployment
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
